### PR TITLE
Db landing page refactor

### PR DESCRIPTION
**Pull request by aminahbl**
Removes source text menu duplication and enhances navigability by using source browser tree on database landing pages and for change menu option on results pages. 

Also lays foundation for source tree re-use.

### CODE REVIEW

**Review by TrebuhD — COMMENTED** [review]
I love the general direction of this change! But are we completely removing this component? I think it still provides a nice different UI to search for texts.

image



Also, the functionality is not the same.

image

image

**Comment by TrebuhD** [comment]
I can resolve those conflicts if needed

**Comment by aminahbl** [comment]
Thanks @TrebuhD. I can't quite tell what's being highlighted by the pictures, it terms of difference in functionality: in terms of what the user can do, they are selecting a file they want to navigate to, only now they have more of an idea about the data structure. 

In any case, the "spec" came from discussion with @sebastian-nehrdich who highlighted redundancy some months ago. We had the briefest preview during this weeks meeting and it seemed to fulfil the spec, but happy to hear what you're uncertain about / still needs discussion.

**Comment by TrebuhD** [comment]
@aminahbl notice that in the last photo the file is not found, even though the user inputs the title of the Sutta. Maybe we should keep this other search as a popup (like the one we used to have in the text and other views)?

**Comment by aminahbl** [comment]
Good point (I was misdirected by the theme change :sweat_smile: ). I guess that is to do with the `search_field` prop that is present on the other menu returns (to memory) and isn't on the `sidebar` menu return. I think this can be created for the tree. Regardless of any other issue, searching in either should produce the exactly the same results.

**Comment by TrebuhD** [comment]
Good idea, I checked `react-arborist` and indeed, this seems to be possible! 

At the moment I'm wondering if we should merge this change as-is, since that seems to be reducing the ability to find content on the site.

If we do decide to remove this search input box, we can probably also remove some network layer code (there's probably an endpoint we don't use anymore).

@ayya-vimala @sebastian-nehrdich

**Comment by aminahbl** [comment]
Yes, this was part of the discussion, the plan in mind is to remove those endpoints. But this is also pending the update to the source text filters two (which this PR was the first stepping stone for - the tree will also be used there).

Good to know about react-arborist! At a guess, we still might need to add an equivalent to the `search_field` prop to the endpoint return, if it is also normalizing funky characters.... @sebastian-nehrdich...?

**Comment by TrebuhD** [comment]
AFAIK the normalisation is also handled by arborist (or the existing endpoint), I didn't do anything special for it on the FE side.

**Comment by aminahbl** [comment]
Oh coool! I just figured Sanskitic and Tibetan characters were, too niche! Nice!

**Comment by aminahbl** [comment]
superseded by #188

**Pull request closed without merging**
